### ISSUE TITLE
PROJECT BULDING 

### ISSUE THREAD

**Issue by NiharikaKolisetty** [NiharikaKolisetty/PFSD-PROJECT#1]
Add project description file

**Comment by 2100032133** [comment]
9. Health & Life Insurance Systems (HLI)
Health insurance is an insurance that covers the whole or a part of the risk of a
person incurring medical expenses, spreading the risk over numerous persons. Life
Insurance is a contract between an insurance policyholder and an insurance company,
where the insurer promises to pay a sum of money in exchange for a premium after a set
period or upon the death of an insured person.
While Health Insurance covers the expenses incurred towards treatment, Life Insurance
can help your family reduce their financial burden in case of your untimely demise.
